import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';

import Layout from 'components/layout/Index';
import Landing from 'components/Landing';
import Contents from 'components/Contents';
import ModalFrame from 'components/Modal/Popup/ModalFrame';
import GettingReady from 'components/Modal/Popup/GettingReady';

const Home: NextPage = () => {
  const [gettingReadyModalOpen, setGettingReadyModalOpen] = useState(false);

  return (
    <>
      <Head>
        <title>고.마.워.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta
          name='description'
          content='Web site created using create-react-app'
        />
        <meta name='title' property='og:title' content='GummyLand' />
        <meta
          name='description'
          property='og:description'
          content='고구맙습니다. 고마운 사우에게 감사인사를 전해보세요:)'
        />
        <meta
          name='image'
          property='og:image'
          content='%PUBLIC_URL%/thumbnail.png'
        />
      </Head>
      {gettingReadyModalOpen && (
        <ModalFrame
          setOnModal={(bool: boolean) => setGettingReadyModalOpen(bool)}
        >
          <GettingReady popupHandler={setGettingReadyModalOpen} />
        </ModalFrame>
      )}
      <Layout popupHandler={setGettingReadyModalOpen}>
        <Landing popupHandler={setGettingReadyModalOpen} />
        <Contents />
      </Layout>
    </>
  );
};

export default Home;
